// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB28C1tzWG4fPGYH0F1_OCYkBQdowGLpYE',
    appId: '1:628884255952:web:95f7b63781421d0e409ad5',
    messagingSenderId: '628884255952',
    projectId: 'ezanvakti-78b20',
    authDomain: 'ezanvakti-78b20.firebaseapp.com',
    storageBucket: 'ezanvakti-78b20.appspot.com',
    measurementId: 'G-1RS1W6YKSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn7G6DjhknsbgyuiCnIOh95sEvGES5Mmk',
    appId: '1:628884255952:android:cb75b91a3811f7ea409ad5',
    messagingSenderId: '628884255952',
    projectId: 'ezanvakti-78b20',
    storageBucket: 'ezanvakti-78b20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRpVGmN0g7A9VlaHg4XQ4V2S8gFW4gf1M',
    appId: '1:628884255952:ios:784d8b9abd7655a3409ad5',
    messagingSenderId: '628884255952',
    projectId: 'ezanvakti-78b20',
    storageBucket: 'ezanvakti-78b20.appspot.com',
    iosClientId: '628884255952-s2fmrd8vdhv719a41i1db7adblbbss90.apps.googleusercontent.com',
    iosBundleId: 'com.example.namazvakitleri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRpVGmN0g7A9VlaHg4XQ4V2S8gFW4gf1M',
    appId: '1:628884255952:ios:394b7fe3d4e146b0409ad5',
    messagingSenderId: '628884255952',
    projectId: 'ezanvakti-78b20',
    storageBucket: 'ezanvakti-78b20.appspot.com',
    iosClientId: '628884255952-v7cc4gg6o83gechqccj22dg71kbct0iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.namazvakitleri.RunnerTests',
  );
}
